### ISSUE TITLE
Adding Request Headers

### ISSUE THREAD

**Issue by Gobble45** [KurzonDax/Plex-to-InfluxDB-Extended#12]
Every time i launch plexInfluxdbCollector.py it crashes. When i run the .py file from Python IDE i get;

> Traceback (most recent call last):
>   File "C:\PlexInflux2\plexInfluxdbCollector.py", line 730, in <module>
>     main()
>   File "C:\PlexInflux2\plexInfluxdbCollector.py", line 725, in main
>     collector = plexInfluxdbCollector(args.silent, config=args.config)
>   File "C:\PlexInflux2\plexInfluxdbCollector.py", line 47, in __init__
>     self._get_auth_token(self.config.plex_user, self.config.plex_password)
>   File "C:\PlexInflux2\plexInfluxdbCollector.py", line 132, in _get_auth_token
>     result = urlopen(req, data=b'').read()
>   File "C:\Python36\lib\urllib\request.py", line 223, in urlopen
>     return opener.open(url, data, timeout)
>   File "C:\Python36\lib\urllib\request.py", line 526, in open
>     response = self._open(req, data)
>   File "C:\Python36\lib\urllib\request.py", line 544, in _open
>     '_open', req)
>   File "C:\Python36\lib\urllib\request.py", line 504, in _call_chain
>     result = func(*args)
>   File "C:\Python36\lib\urllib\request.py", line 1361, in https_open
>     context=self._context, check_hostname=self._check_hostname)
>   File "C:\Python36\lib\urllib\request.py", line 1318, in do_open
>     encode_chunked=req.has_header('Transfer-encoding'))
>   File "C:\Python36\lib\http\client.py", line 1239, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "C:\Python36\lib\http\client.py", line 1280, in _send_request
>     self.putheader(hdr, value)
>   File "C:\Python36\lib\http\client.py", line 1217, in putheader
>     raise ValueError('Invalid header value %r' % (values[i],))
> ValueError: Invalid header value b'Basic amFtZXMuYWxsZW4yNzhAZ21haWwuY29tOmljSkhqS0ZHRUoyNDJRalVtSnphUEZqa3ExQ2lxdm5J\nMjJCVGZ3ZDJqTXdXcFB5V0R5

`

running on Windows Server 2016 x64. I have Python 3.6 and 2.7 installed in seperate directories.

**Comment by KurzonDax** [comment]
To be honest, I haven't tested much with running the script under Windows.  I'll look in to this a bit later today, but in looking at the trace, I'm sort of stumped on where that invalid header value is coming from.  Would you mind posting a copy of your config.ini (obviously remove user names and passwords for Plex and Influx)?

Edit: Also, what version of Plex server are you running?

**Comment by Gobble45** [comment]
```
[GENERAL]
Delay = 2
LibraryDelay = 1800
Output = True

[INFLUXDB]
Address = 192.168.0.14
Port = 8086
Database = plex_data
Username =
Password = 
Verify_SSL = False

[PLEX]
Username = 
Password = 
# List of servers seperated by a comma.
# Example: 192.168.1.20,10.0.0.20
Servers = 192.168.0.14

[LOGGING]
Enable = True
# Valid Options: critical, error, warning, info, debug
Level = debug
LogFile = output.log
# Removes things such as server names and ip addresses from logs
CensorLogs = True

# Any log messages greater than or equal to this number will also be printed to the console
# Output must also be true under GENERAL
# DEBUG: 0
# INFO: 1
# WARNING: 2
# ERROR: 3
# CRITICAL: 4
PrintThreshold = 0
```

Plex server: Version 1.13.5.5291

**Comment by sojab0on** [comment]
that config looks like the basic version. 
You need to change the username password and ips to reflect to the right servers. 

Also under windows python can be a bit flaky,

I sugest you run a linux based docker container for this that runs a bit better
