### ISSUE TITLE
RemoteDisconnected Error on Start

### ISSUE THREAD

**Issue by n1nj4888** [KurzonDax/Plex-to-InfluxDB-Extended#13]
I’m getting the following error when I try to run “python3 plexInfluxdbCollector.py” - Any idea what I’m doing wrong? I’ve installed pip3 and the following python packages - plexapi, requests, influxdb...

```
<USER>@ubuntu18-vm:~/scripts/Plex-to-InfluxDB-Extended$ python3 plexInfluxdbCollector.py 
Loading Configuration File config.ini
Traceback (most recent call last):
  File "plexInfluxdbCollector.py", line 730, in <module>
    main()
  File "plexInfluxdbCollector.py", line 725, in main
    collector = plexInfluxdbCollector(args.silent, config=args.config)
  File "plexInfluxdbCollector.py", line 26, in __init__
    self.config = configManager(silent, config=config)
  File "plexInfluxdbCollector.py", line 632, in __init__
    self._validate_plex_servers()
  File "plexInfluxdbCollector.py", line 683, in _validate_plex_servers
    urlopen(server_url)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
<USER>@ubuntu18-vm:~/scripts/Plex-to-InfluxDB-Extended$ 
```

**Comment by n1nj4888** [comment]
It appears that, if Secure Connections is set as "Required" on the Plex Server itself then the script does not get a response from the server?

Does the script have any configuration options to support connecting to a Plex Server with Secure Connections set as "Required"?
